[package]
name = "webhook-429-test"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
reqwest = { version = "0.13.0", features = ["json"] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
